#trigger:
#- main

pool:
  vmImage: windows-latest

variables:
  BROWSER_TYPE: 'firefox'

#schedules:
#- cron: "0 */6 * * 1-5"
#  displayName: Run each 6 hours
#  always: true
#  branches:
#    include:
#    - main

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '6.0.x'
  displayName: 'Use .NET SDK'

- task: DotNetCoreCLI@2
  displayName: New Manifest for tool
  inputs:
    command: custom
    custom: 'new '
    arguments: tool-manifest

- task: DotNetCoreCLI@2
  displayName: 'Install PlayWright CLI'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install Microsoft.Playwright.CLI'

- task: DotNetCoreCLI@2
  displayName: 'Build Test Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: CmdLine@2
  displayName: 'Install Browsers for Playwright'
  inputs:
    script: |
      cd playwright-specflow-pom-dotnet-main/PlaywrightSpecFlowPOM
      ls
      pwsh bin/Debug/net6.0/playwright.ps1 install

- task: CmdLine@2
  displayName: 'Run Test'
  inputs:
    script: |
      cd playwright-specflow-pom-dotnet-main/PlaywrightSpecFlowPOM
      ls
      echo '$(System.DefaultWorkingDirectory)'
      dotnet test --settings:chromium.runsettings
      dotnet test --settings:firefox.runsettings
      dotnet test --settings:webkit.runsettings

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  displayName: 'Publish Artifacts'
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: PlaywrightReport

- task: SpecFlowPlus@0
  displayName: 'LivingDoc with FeatureFolder generatorSource'
  condition: succeededOrFailed()
  inputs:
    generatorSource: 'FeatureFolder'
    projectFilePath: '$(System.DefaultWorkingDirectory)/playwright-specflow-pom-dotnet-main/PlaywrightSpecFlowPOM'
    projectName: 'Amazon Find Book Test'
    testExecutionJson: '$(System.DefaultWorkingDirectory)/playwright-specflow-pom-dotnet-main/PlaywrightSpecFlowPOM/bin/Debug/net6.0/TestExecution.json'
    projectLanguage: 'en'
    bindingAssemblies: '$(System.DefaultWorkingDirectory)\playwright-specflow-pom-dotnet-main\PlaywrightSpecFlowPOM\bin\Debug\net6.0\PlaywrightSpecFlowPOM.dll'
    enabled: false
    continueOnError: true
    condition: always()
    timeoutInMinutes: 10
